/* eslint-disable */
// Generates a short mono 16-bit PCM WAV (a soft 440Hz tone) and writes it,
// base64-encoded, into src/assets/sampleAudio.ts so it can be bundled with the app.
// Run: npm run gen:audio

const fs = require('fs');
const path = require('path');

const SAMPLE_RATE = 16000;
const SECONDS = 1.0;
const FREQ = 440;
const AMPLITUDE = 0.25;

const numSamples = Math.floor(SAMPLE_RATE * SECONDS);
const dataSize = numSamples * 2; // 16-bit mono
const buffer = Buffer.alloc(44 + dataSize);

// RIFF header
buffer.write('RIFF', 0);
buffer.writeUInt32LE(36 + dataSize, 4);
buffer.write('WAVE', 8);
// fmt chunk
buffer.write('fmt ', 12);
buffer.writeUInt32LE(16, 16); // PCM chunk size
buffer.writeUInt16LE(1, 20); // audio format = PCM
buffer.writeUInt16LE(1, 22); // channels = 1
buffer.writeUInt32LE(SAMPLE_RATE, 24);
buffer.writeUInt32LE(SAMPLE_RATE * 2, 28); // byte rate
buffer.writeUInt16LE(2, 32); // block align
buffer.writeUInt16LE(16, 34); // bits per sample
// data chunk
buffer.write('data', 36);
buffer.writeUInt32LE(dataSize, 40);

for (let i = 0; i < numSamples; i++) {
  // Apply a short fade in/out to avoid clicks.
  const fade = Math.min(1, i / 800, (numSamples - i) / 800);
  const sample = Math.sin((2 * Math.PI * FREQ * i) / SAMPLE_RATE) * AMPLITUDE * fade;
  buffer.writeInt16LE(Math.max(-1, Math.min(1, sample)) * 32767, 44 + i * 2);
}

const b64 = buffer.toString('base64');
const out = `// AUTO-GENERATED by scripts/gen-audio.js. Do not edit by hand.
// A ~1s 440Hz tone (16kHz mono 16-bit WAV) bundled as the sample clip for triggers.
export const SAMPLE_AUDIO_B64 = '${b64}';
`;

const outPath = path.join(__dirname, '..', 'src', 'assets', 'sampleAudio.ts');
fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, out);
console.log(`Wrote ${outPath} (${b64.length} base64 chars)`);
