/* eslint-disable */
// Records a walkthrough video + key-state screenshots of an elder-facing design
// preview served by `expo start --web`. Walks BOTH paths:
//   1) Fine path:   Simulate Fall -> "I'm OK" -> resolved -> idle
//   2) Emergency:   Simulate Fall -> (no response) -> auto-escalate -> notified
//
// Usage: node scripts/record-design.js <url> <outDir> <label>
//   node scripts/record-design.js http://localhost:8088 ../design-videos/design-a-aurora Aurora

const path = require('path');
const fs = require('fs');
const { chromium } = require('playwright');

const URL = process.argv[2] || 'http://localhost:8088';
const OUT_DIR = path.resolve(process.argv[3] || './design-video-out');
const LABEL = process.argv[4] || 'design';

const VIEW = { width: 520, height: 1000 };
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

async function shot(page, name) {
  await page.screenshot({ path: path.join(OUT_DIR, `${name}.png`) });
  console.log(`  shot: ${name}.png`);
}

(async () => {
  fs.mkdirSync(OUT_DIR, { recursive: true });
  const browser = await chromium.launch();
  const context = await browser.newContext({
    viewport: VIEW,
    recordVideo: { dir: OUT_DIR, size: VIEW },
    deviceScaleFactor: 2,
  });
  const page = await context.newPage();
  console.log(`[${LABEL}] loading ${URL}`);
  await page.goto(URL, { waitUntil: 'load', timeout: 120000 });

  // First web bundle can be slow; wait for the idle control to appear.
  await page.getByText('Simulate Fall').first().waitFor({ timeout: 120000 });
  await sleep(4000); // dwell on the breathing idle orb
  await shot(page, '1-idle');

  // ---- Path 1: fine ----
  await page.getByText('Simulate Fall').first().click();
  await page.getByText('CHECK-IN').first().waitFor({ timeout: 10000 });
  await sleep(2600); // show the question + countdown ticking
  await shot(page, '2-checkin');
  await page.getByText("I’m OK").first().click();
  await page.getByText('Glad you’re okay').first().waitFor({ timeout: 8000 });
  await sleep(1200);
  await shot(page, '3-resolved');
  await sleep(2600); // returns to idle

  // ---- Path 2: emergency (auto-escalate on no response) ----
  await page.getByText('Simulate Fall').first().waitFor({ timeout: 8000 });
  await page.getByText('Simulate Fall').first().click();
  await page.getByText('CHECK-IN').first().waitFor({ timeout: 10000 });
  await sleep(3000);
  // Let the countdown run out -> auto escalate.
  await page.getByText('Reaching your caretaker').first().waitFor({ timeout: 14000 });
  await sleep(1200);
  await shot(page, '4-escalating');
  await page.getByText('Caretaker notified').first().waitFor({ timeout: 8000 });
  await sleep(1500);
  await shot(page, '5-escalated');
  await sleep(1500);

  await context.close(); // finalizes the video
  await browser.close();

  // Rename the autogenerated video to a stable name.
  const files = fs.readdirSync(OUT_DIR).filter((f) => f.endsWith('.webm'));
  if (files.length) {
    const newest = files
      .map((f) => ({ f, t: fs.statSync(path.join(OUT_DIR, f)).mtimeMs }))
      .sort((a, b) => b.t - a.t)[0].f;
    const dest = path.join(OUT_DIR, 'walkthrough.webm');
    fs.renameSync(path.join(OUT_DIR, newest), dest);
    console.log(`[${LABEL}] video -> ${dest}`);
  }
  console.log(`[${LABEL}] done. Artifacts in ${OUT_DIR}`);
})().catch((err) => {
  console.error('record failed:', err);
  process.exit(1);
});
